version: "{build}"

clone_depth: 1

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - bundler --version
  - bundle install

build: "off"

test_script:
  - bundle exec rake

environment:
  matrix:
    - ruby_version: "24"
    - ruby_version: "24-x64"
    - ruby_version: "25"
    - ruby_version: "25-x64"
    - ruby_version: "26"
    - ruby_version: "26-x64"
