version: "{build}"

clone_depth: 1

install:
  - cinst wget
  - cmd: wget https://curl.haxx.se/ca/cacert.pem -O C:\cacert.pem
  - SET SSL_CERT_FILE=C:\cacert.pem
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - bundler --version
  - bundle install

build: off

test_script:
  - bundle exec rake

environment:
  matrix:
    - ruby_version: "24"
    - ruby_version: "24-x64"
    - ruby_version: "25"
    - ruby_version: "25-x64"
    - ruby_version: "26"
    - ruby_version: "26-x64"
